# Generated by Django 4.2.7 on 2025-05-26 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneratedScript",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "script_type",
                    models.CharField(
                        choices=[
                            ("cold_call", "Cold Call"),
                            ("email", "Email"),
                            ("in_person", "In Person"),
                        ],
                        max_length=20,
                    ),
                ),
                ("location_name", models.CharField(max_length=255)),
                ("location_category", models.CharField(max_length=100)),
                ("machine_type", models.CharField(max_length=50)),
                ("script_content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-created_at"],},
        ),
    ]
